### PR TITLE
Delete file when user delete everything in textarea

### PR DESCRIPTION
**Pull request by qex**
The main purpose of this PR is to avoid empty files leaving.

Original code will leave a 0 byte file when user clear textarea, now this file will be removed.

Additionally I've made two minor optimizations, change rand() to mt_rand() and pick strlen() out of loop.

Which will both speed up the script running a tiny little bit.

Based on commit [75c1f37](https://github.com/pereorga/minimalist-web-notepad/commit/75c1f37a5b2213bc62f02b11d0b302101904ceae), recover the suffix slash of curl to increase accuracy.

I've discovered this project 2 hours ago, and captivated by it immediately.

Thank you for bringing us such an amazing notepad.  :yum:

### CODE REVIEW

**Comment by qex** [comment]
Got that, I'll do that separately.

Every curl user agent always end with a slash I've seen, however I don't think there's other user-agent start with curl besides curl itself too.

Add that slash probably make the code more strict ?

**Comment by pereorga** [comment]
> Add that slash probably make the code more strict ?

It could, I'm unsure on that one. But the only downside I see here is potentially giving a raw file to a user not using curl (but using a client that starts with curl). I think that if the user agent starts with 'curl', it probably means that the client is curl, a fork of curl, or a client that behaves like curl, and then the raw output should be fine IMO.

**Comment by qex** [comment]
Maybe there's some browser named "Curlews" or "Curlicue" and doesn't start their user-agent with "Mozilla/"?

Well just kidding, ignore me. :stuck_out_tongue_winking_eye:

**Comment by pereorga** [comment]
Curlews/232 or Curlicue/13 won't match either, because the capital letter. But that's a valid point :)

FWIW, I just tried to search Google/Bing using 'curl' and 'Curlews' user agents and I get a 403 response in Google, and weird HTML in Bing.

**Pull request closed without merging**
