### PR TITLE
Update to allow dash/hyphen in note name

### PR DESCRIPTION
**Pull request by domOrielton**
Update to allow note names with a dash or hyphen - this would enable easily readable names if required e.g. 
/notes-roadmap 
/notes-useful-links 
/notes-issues, etc.    I'm using this on my install so hope it helps someone else.  Dom

### CODE REVIEW

**Comment by pereorga** [comment]
Merged, thanks!

**Comment by domOrielton** [comment]
Glad to help. Also wanted to check with you that you are ok with me forking your code into another project - domOrielton/minimal-web-notepad? Pretty sure the license covers it but I always like to ask! Your code is the basis for it, I've just added some additional functionality (and size so it's around 11kb minified/gzipped) by basically adding a header to the notes text file when saving when needed - something like `[header] &noteName=some-note-name&noteHash=bWluZGZ1bG5lc3M=&password=$2y$10$a01tS0J11QStOEpeKf4S5uaerKC.H/5CLMGFaw3IYPhv9tlwG9B3e&allowReadOnlyView=1
`
Hope this is ok and thank you for an excellent piece of core code to start from.   Dom

**Comment by pereorga** [comment]
That is completely of course, thanks for letting me know.

**Comment by twamix** [comment]
hi，Can you add a password protection function to the article?

**Pull request merged**
