### PR TITLE
An attempt to remove $name

### PR DESCRIPTION
**Pull request by qex**
It is all about the question "what is minimalist".

Will the code looks clear now?

### CODE REVIEW

**Comment by pereorga** [comment]
That looks good.

.htaccess should also be changed. And the nginx instructions in the README

**Comment by qex** [comment]
Yeah I will go with that.

And actually it doesn't cause more characters transfer because the rewrite.

No one visit note using `/?f=xxxxx` or `/?note=xxxxx`, they just use `/xxxxx` and everything are same.

**Comment by pereorga** [comment]
> No one visit note using /?f=xxxxx or /?note=xxxxx, they just use /xxxxx and everything are same.

True, I forgot that JS code is using a relative path. It's only the `text` in POST then that requires more chars. But that's fine.

`$path = "$data_directory/{$_GET['note']}";`

Wouldn't that be more readable with `$data_directory . '/' . $_GET['note']` or `"$data_directory/" . $_GET['note']` ?

**Comment by pereorga** [comment]
Great!

**Comment by qex** [comment]
Let me see, it makes little difference, however without `{}` the code looks more clear.

**Comment by qex** [comment]
Yeah it is great!

**Pull request merged**
