### PR TITLE
php: Remove sanitizeString function

### PR DESCRIPTION
**Pull request by pereorga**
- Remove sanitizeString()
- Switch empty() for isset(), to allow note names such as '0'.
- Slightly improved comments

### CODE REVIEW

**Comment by pereorga** [comment]
@qex what do you think?

**Comment by qex** [comment]
This is hard to do, you need to change the logic of `sanitizeString($_GET['f']) !== $_GET['f']`.

that can be done, and will make code a little harder to read I think.

**Comment by qex** [comment]
New code will act like this:

```
if ( isset( $_GET['f'] ) ) {
  $name = preg_replace( '/[^a-zA-Z0-9]+/', '', $_GET['f'] );
}

// no, there's no else, because we need name
if ( ! isset( $_GET['f'] ) || $name !== $_GET['f'] ) {
  // do creation job
}
```

or you can define the creation job as a function and call it twice.

**Comment by qex** [comment]
Oh my mistake, I didn't notice this is a PR so I didn't see your code ...

you made the point, it is a clever move!

**Comment by qex** [comment]
Oh my mistake, I didn't notice this is a PR so I didn't see your code ...

you made the point, it is a clever move!

what if change `if ( isset( $_GET['f'] ) ...` line into

```
if ( isset($_GET['f' ]) && isset( $_GET['f'][0] ) && $_GET['f'] === preg_replace('/[^a-zA-Z0-9]+/', '', $_GET['f'] ) ) {
```

second isset is a small trick equals to `strlen() !== 0` but faster, then you can just put next section into else.

**Comment by pereorga** [comment]
That makes sense!

**Comment by qex** [comment]
You can remove the two new branch auto-generate by this PR make the project clean.

**Comment by pereorga** [comment]
Thanks again!

**Pull request closed without merging**
