### PR TITLE
Better docker image availability

### PR DESCRIPTION
**Pull request by Its4Nik**
Hey y'all I wrote a little github actions script to build and publish an image each time there is a push to master.

It's plug and play cause it leverages the built in github actions veriables.

- Nik

### CODE REVIEW

**Comment by pereorga** [comment]
@Its4Nik I appreciate the interest, but honestly I don't think it is the right fit for the project. I don't want to maintain Docker images, even if they are pushed automatically. At some point we had a Dockerfile in the repository, but I removed it from the main branch, because I thought using Docker for a single PHP file is overkill, and this project aims for extreme minimalism.

**Comment by Its4Nik** [comment]
> @Its4Nik I appreciate the interest, but honestly I don't think it is the right fit for the project. I don't want to maintain Docker images, even if they are pushed automatically. At some point we had a Dockerfile in the repository, but I removed it from the main branch, because I thought using Docker for a single PHP file is overkill, and this project aims for extreme minimalism.

@pereorga 
Okay i see that, but still a lot of people prefer docker, thats why my idea would be that i maintain the docker branch with this workflow. Wouldn't that be a good compromise?

**Comment by pereorga** [comment]
@Its4Nik yes that's ok, but then I believe a fork is more appropriate than a branch

**Comment by Its4Nik** [comment]
> @Its4Nik yes that's ok, but then I believe a fork is more appropriate than a branch

Okay then i would just maintain my fork i already created, and maybe you could add it to the readme as little link yk?

**Comment by pereorga** [comment]
> Okay then i would just maintain my fork i already created, and maybe you could add it to the readme as little link yk?

I'm sorry, but I don't plan to add links to other forks in the README.

**Comment by Its4Nik** [comment]
> > Okay then i would just maintain my fork i already created, and maybe you could add it to the readme as little link yk?
> 
> I'm sorry, but I don't plan to add links to other forks in the README.

Oh okay i see then i'll just maintain the fork without any connection ig

**Pull request closed without merging**
