### PR TITLE
remove $length for now

### PR DESCRIPTION
**Pull request by qex**
Yeah, I'd willing to~

### CODE REVIEW

**Comment by pereorga** [comment]
Sorry for merging too fast. I've also applied some cosmetics

**Comment by qex** [comment]
Never mind, I saw you still leave $length there?

**Comment by pereorga** [comment]
Yes, I left it for now. I'm a bit unsure of what's best. What do you think?

**Comment by qex** [comment]
I've thinking about this for half an hour.

the conclusion for now is, leave that 5 there, and write a comment like `if you need to change the default name length of note, change that 5 below`.

**Comment by pereorga** [comment]
What about renaming the variable to `$default_name_length`. And then without the comment.

**Comment by qex** [comment]
I've done that before, put this line above `$characters` and below `if`.

It is still an extra variable for rarely executed if condition, but it is useable than my first `$size`.

**Comment by qex** [comment]
After all in the original code this variable is not a explicit config also.

If we need to add some customization, write it as `$name_length`, not default because it is modifiable.

In other way if we need to keep the original minimalist type, leave a 5 there.

**Comment by pereorga** [comment]
> If we need to add some customization, write it as $name_length, not default because it is modifiable.

Done.

> In other way if we need to keep the original minimalist type, leave a 5 there.

Hard decision, but I like it now. Minimalist also means less comments. We can switch to const in the future, when we don't care about older PHP versions.

**Comment by pereorga** [comment]
I see what you meant about $randomString variable. Changed now.

**Comment by qex** [comment]
Yup, for now the lowest version to run the notepad is 5.0.0, limited by file_put_contents.

If we remove that, this pad can run on php 4.3.0, limited by file_get_contents, that is amazing.

that will run almost every where. just upload, and run, that is how I love this project.

I think using variable as config is nothing bad, there's no need to force using constance isn't it?

**Comment by pereorga** [comment]
yes, it's OK :)

**Comment by qex** [comment]
Seems it is near 0 o'clock at your time ?

Time to sleep! I will continue PR this project when I got new ideas.

for example change print to echo, change <?php print $foo; ?> to <?=$foo?>, etc.

some customization of no importance in total.

**Comment by pereorga** [comment]
Cool, have a good day. And thanks!

**Comment by qex** [comment]
You're welcome. It is my pleasure to make a great project better~ :wink:

**Pull request closed without merging**
