### PR TITLE
Add optional encryption

### LINKED ISSUE #41: End-to-end encryption
If a fragment (`#something`) is appended to the URL, this should be used for encryption. It can be completely implemented using Web Crypto API ([SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto)) and thus only increases size by very few lines of code.

I can provide you some sample code, once my question on [StackExchange](https://crypto.stackexchange.com/q/81409/66922) is answered.

It would also be possible to use a human-readable password which the users has to enter in a textbox such that it is not shown on screenshots. [Key derivation](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey) should be used in this case.

### PR DESCRIPTION
**Pull request by darkdragon-001**
Cryptography
- Use AES-GCM-256 for encryption
- Use PBKDF2 with SHA-256 and 100000 iterations for key derivation

Environment variables
- Enable with environment variable `MWN_ENCRYPTION`
- Set salt with environment variable `MWN_CRYPTO_SALT`

Behavior
- A human-readable password (16 characters) will be automatically be generated for empty notes
- The password will be appended to the URI as fragment `#password`
- The IV (12 bytes) is prepended to the ciphertext
- Everything is base64 encoded (33% overhead)

Documentation
- Add section about environment variables to `README.md`

Fixes
- Fix note identifier generation such that characters can appear multiple times

Fixes #41

### CODE REVIEW

**Comment by darkdragon-001** [comment]
One open question is the handling of existing (unencrypted) notes. Should they be encrypted?

If so, I have to choose a different binary format to differentiate between unencrypted and encrypted-with-another-password.

**Comment by pereorga** [comment]
Hi @darkdragon-001, thanks for the pull requests. I would like to review them soon, but my time is limited. I think encryption is a nice to have option, but I'm unsure about adding complexity to the project. At the same time, I would also be interested in adding DOS protection (such as preventing getting thousands of requests uploading 1 MB each, etc. - this has happened), which is probably not simple either...

On any case, making smaller pull requests may help. I'm also not especially happy about increasing PHP/browser requirements.

**Comment by darkdragon-001** [comment]
Most of the changed lines are only indentation changes because I had to wrap some global code into a `onload` function. This basically adds `crypt.js` and calls the three functions `generateKey()`, `encrypt()` and `decrypt()` at the right places.

Using the docker approach, I suggest outsourcing such things as SSL-keys, DOS protection etc. to a separate (e.g. nginx) container. One can easily start multiple containers together with docker-compose. This keeps applications small and reduces complexity.

**Comment by pereorga** [comment]
I have merged this into a separate branch. For now, I'm not sure I want to provide this in the default branch. But I'll add a link in the README.

Regarding the other general JavaScript changes (`async`, `let`, `const`, etc.) I don't plan to merge them in the default branch. I understand why these changes should be preferred on most circumstances, but I also like to support ancient browsers (< 0.5% share).

In the default branch, I will also keep the `XMLHttpRequest` upper in the code. I don't feel strong about this, but I consider that sending the data is more prioritary than updating the print version of the page.

I will also not add the `str_repeat()` call in the default branch. I like the idea security-wise, but at the same time, I think that non-repeating characters are also less ambiguous to the human eye, when reading the string (and minor: it would add an extra function call).

I plan to merge the documentation changes to the default branch too.

Any comments or other suggestions, please let me know.

Thanks again

**Comment by darkdragon-001** [comment]
> Regarding the other general JavaScript changes (`async`, `let`, `const`, etc.) I don't plan to merge them in the default branch. I understand why these changes should be preferred on most circumstances, but I also like to support ancient browsers (< 0.5% share).

Do you know any possibility to remove `async`?
I am only aware of passing callbacks around, but for minimalist principles I preferred `await`.

> I will also not add the `str_repeat()` call in the default branch. I like the idea security-wise, but at the same time, I think that non-repeating characters are also less ambiguous to the human eye, when reading the string (and minor: it would add an extra function call).

5 characters is already little entropy, removing ambiguous characters and avoiding duplicate characters reduces it even further and makes guessing attacks quite likely to succeed. When the notes are not even encrypted, _everyone_ can just read _all_ documents.

**Comment by pereorga** [comment]
> 5 characters is already little entropy, removing ambiguous characters and avoiding duplicate characters reduces it even further and makes guessing attacks quite likely to succeed. When the notes are not even encrypted, everyone can just read all documents.

That could certainly be an issue that can be improved by repeating characters and increasing the number of them. But I expect users to choose their own names most of the time, especially if they care about having their notes discovered. That also doesn't apply on non-self-hosted servers, where the owner of the host can already discover everything.

> Using the docker approach, I suggest outsourcing such things as SSL-keys, DOS protection etc. to a separate (e.g. nginx) container. One can easily start multiple containers together with docker-compose. This keeps applications small and reduces complexity.

I've thought about that, and yes, it makes sense to do it in another layer, but, at the same time, this is truly a security vulnerability in the app itself. And DOS is a big concern now, especially because it's very easy to fill the disk or create an insane number of files.

**Comment by darkdragon-001** [comment]
Just add a container for [Let's encrypt](https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71) and add [DDOS protection](https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus/) to nginx. This is nothing which should be built into the app itself. If one is not using Docker, one has to manually configure apache/nginx anyways and add it there.

**Comment by troilus** [comment]
Hi, thanks for encrypt option, but how to enable the option? I add the environment variables into docker-compose file like this:

```
version: “2.4”
services:
  minimalist-web-notepad:
    build: .
    container_name: minimalist-web-notepad
    restart: always
    ports:
     - "9324:80"
    volumes:
     - minimalist-web-notepad:/var/www/minimalist-web-notepad/_tmp
    environment:
     - MWN_ENCRYPTION
     - MWN_CRYPTO_SALT
volumes:
  minimalist-web-notepad:
```
But doesn't have differences.

**Comment by darkdragon-001** [comment]
@troilus 
1. It has only been merged to the "encryption" branch and not the default one. Are you using that one?
2. `MWN_ENCRYPTION` needs to be set to `true`, `MWN_CRYPTO_SALT` should either be a random string or unset to use the default one for testing purposes.

**Comment by troilus** [comment]
> @troilus
> 
> 1. It has only been merged to the "encryption" branch and not the default one. Are you using that one?
> 2. `MWN_ENCRYPTION` needs to be set to `true`, `MWN_CRYPTO_SALT` should either be a random string or unset to use the default one for testing purposes.

Thanks, fixed after using:
```
    environment:
      MWN_ENCRYPTION: 'TRUE'
      MWN_CRYPTO_SALT: 'xxx'
```

**Pull request merged**
