### PR TITLE
Add feature: can call XXXXX~raw for have a raw text (for not apache webserver)

### PR DESCRIPTION
**Pull request by blackout314**

### CODE REVIEW

**Comment by pereorga** [comment]
Thank you for the PR. I fail to see why this is better to what we have. Also, note that this is reverting some unrelated code changes.

**Comment by blackout314** [comment]
hello, is for for not apache webserver

**Comment by pereorga** [comment]
I see the problem, passing `?raw` doesn't seem to work, even in Apache.

I think this can be fixed in `.htaccess` (adding `[QSA]`) and we may just need to update Nginx instructions.

I don't think we need to change the PHP code.

**Comment by blackout314** [comment]
okk

**Comment by pereorga** [comment]
.htaccess file issue has been.fixed in dab338d96663039f22aea511dba1b0e98dcef39b (see e.g. https://notes.orga.cat/whatever?raw)

I tried to update Nginx instructions in 38459b4d713d4a18098ab669166239030851487d, although I haven't tested them.

Thanks!

**Pull request closed without merging**
