### PR TITLE
remove generateRandomString() since it run 1 time max

### PR DESCRIPTION
**Pull request by qex**
How about this PR? :grin:

### CODE REVIEW

**Comment by pereorga** [comment]
Hmmm, I have mixed feelings about this one. I think I prefer a function here because for me it's easier to read.

**Comment by qex** [comment]
Well, is that worth for one extra function and one extra function call for easier to read?

An extra variable is unacceptable, an extra function isn't?

**Comment by pereorga** [comment]
> Well, is that worth for one extra function and one extra function call for easier to read?
> An extra variable is unacceptable, an extra function isn't?

Hard to say. Removing functions and additional variables are both micro-optimizations. However, sometimes, removing a function and a variable can make the code harder to read. That may be subjective

**Comment by qex** [comment]
I think the difference between two ways is generate hash using in a function or in a condition body.

As comment says, `User has not specified a valid name, generate one`, and the code of hash generation is right below this line.

In my opinion it is easier to find backward finding a function named "generateRandomString()" ?

**Comment by pereorga** [comment]
Your are probably right.

I would remove the `length` variable then. It made sense when it was as a parameter of a reusable function, but not in a code block. Now we can just put a 5.

**Comment by qex** [comment]
Wooo, I am adding some new code when you reply ... 

is_file() is a little faster than file_exists() since it doesn't affect in directories.

besides I repaired potential warning on curl visit non-exists note.

**Comment by pereorga** [comment]
I like the is_file() change.

**Comment by qex** [comment]
Simply remove the $length is really good for script running, but how about reading? 

if some user wants to change the default hash length, should we raise this variable to top of the file as a config?

**Comment by pereorga** [comment]
Yes, that makes sense.

**Comment by qex** [comment]
Well it is strange that config variables using long snake way and hash generator using the camel case way.

Should I unify them?

**Comment by qex** [comment]
Well I am on to another thing.

If raised that variable as config, it is absolutely useless when visit an exists note.

I've got no idea about this, maybe we should just write a 5 as you said?

**Comment by pereorga** [comment]
> Well it is strange that config variables using underscore case way and hash generator using the camel case way.

> Should I unify them?

That could be done. Also, constants in uppercase could be used for configuration

**Comment by qex** [comment]
So the next step we will change $base_url into BASE_URL ?

Well, in my opinion this would be a bad idea, define() is slow somehow, `const` is faster but it only works above php 5.3.

**Comment by pereorga** [comment]
Then let's merge it as it is for now, with the length variable removed. Other changes can be discussed in other PRs.

I think it's acceptable to keep cammelCase for functions, and underscores in variables. But I am happy to merge PR that unify things.

**Pull request merged**
